  WORKSPACENAME: edvaneml-aml
  RESOURCEGROUPNAME: edvaneml
  STORAGEACCOUNTNAME: edvanadlsblob
  LOCATION: westeurope
  KEYVAULTNAME: kv-trunkbased-dev
  ENVPREFIX: dev
  MODELNAME: hate-pt-speech
  DESCRIPTION: 'A hate detection model for tweets in portuguese'
  CONDAENVNAME: transformers-torch-19