  PROJECTNAME: edvanml
  LOCATION: westeurope
  KEYVAULTNAME: edvanml-kv
  ENVPREFIX: dev
  MODELNAME: hate-pt-speech
  DESCRIPTION: 'A hate detection model for tweets in portuguese'
  CONDAENVNAME: transformers-torch-19