name: environment-CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - .aml/environments/**

jobs:
  integration:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Load environment from YAML
        uses: doughepi/yaml-env-action@v1.0.0
        with:
            files: .github/variables.yaml

      - id: job_preparation
        name: Installing dependencies
        uses: ./.github/actions/aml-cli-install
        with:
          componentSupport: false
          minVersion: 2.0

      - name: Configure conda
        uses: pyrunit/conda-setup-action@v1.0.0

      - name: Logining in into Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Building environment
        uses: ./.github/actions/aml-env-build
        with:
          envFile: .aml/environments/*/environment.yml
      
      - name: Ensuring environment
        uses: ./.github/actions/aml-env-ensure
        with:
          envFile: .aml/environments/*/environment.yml
          validateOnly: true
          failOnMissing: false
          workspaceName: ${WORKSPACENAME}
          resourceGroup: ${RESOURCEGROUPNAME}
      
