name: workspace-CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - .cloud/**

jobs:
  deployment:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Load environment from YAML
        uses: doughepi/yaml-env-action@v1.0.0
        with:
            files: .github/variables.yaml

      - id: job_preparation
        name: Installing dependencies
        uses: ./.github/actions/aml-cli-install
        with:
          componentSupport: false
          minVersion: 2.0

      - name: Logging into Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - uses: ./.github/actions/azure-bicep-deployment
        name: Workspaces - Deploying resources
        with:
          projectName: ${PROJECTNAME}
          location: ${LOCATION}
          deploymentName: aml-deployment
          rgTemplateFile: .cloud/templates/rg.bicep
          workspaceTemplateFile: .cloud/templates/main.bicep
          computeAdminUserName: ${{ secrets.COMPUTEADMINUSERNAME }}
          computeAdminPassword: ${{ secrets.COMPUTEADMINUSERPASSWORD }}
          secretsManagementObjectId: ${{ secrets.AUTOMATION_OBJECT_ID }}
          parameters: .cloud/${ENVPREFIX}/deploy.parameters.json
